{{- $dotenv := .Values.envFrom.dotenv | default "" -}}
{{- $secData := (include "env.secretData" (dict "dotenv" $dotenv "strip" .Values.envFrom.stripPrefixes) | fromYaml) -}}
{{- if $dotenv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "env.secretName" . }}
  annotations:
    env.zota/debug: "secret-keys={{ join \",\" (keys $secData) }}"
type: Opaque
stringData:
{{- range $k, $v := $secData }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}