apiVersion: v2
name: minimal
version: 0.1.0
type: application

dependencies:
  - name: postgresql
    alias: postgres
    version: 15.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgres.enabled