apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-wait-pullsecret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"          # выполнится раньше остальных хуков
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      serviceAccountName: {{ default "default" .Values.hooks.serviceAccount }}
      restartPolicy: Never
      containers:
        - name: wait
          image: bitnami/kubectl:1.30
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -e
              NS="{{ .Release.Namespace }}"
              SECRET="{{ .Values.registry.pullSecretName | default "gitlab-registry-ro" }}"
              echo "Waiting for secret ${SECRET} in ns ${NS}..."
              for i in $(seq 1 {{ default 60 .Values.hooks.waitSeconds }}); do
                if kubectl -n "${NS}" get secret "${SECRET}" >/dev/null 2>&1; then
                  echo "Secret found."
                  exit 0
                fi
                sleep 1
              done
              echo "Timeout waiting secret ${SECRET}"
              exit 1